### ISSUE TITLE
内测账号

### ISSUE THREAD

**Issue by Tlaster** [OpenWeen/OpenWeen.UWP#1]
你可以在这里留下你的live id用于内测

**Comment by czhang03** [comment]
对不起对不起，我留错了
13501393281@outlook.com
能不能帮我把我朋友也加进去
shenshi0826@126.com

**Comment by suzumiya123** [comment]
daiwu598@hotmail.com

**Comment by bshumaster** [comment]
fjh-wp@outlook.com

**Comment by CyanSpeed** [comment]
aureate-sunshine@live.com

**Comment by QZQ-QSQ** [comment]
qiuzhongqiang@hotmail.com  谢谢
