### ISSUE TITLE
完了完了 weico的apikey也失效了

### ISSUE THREAD

**Issue by MrRegret** [OpenWeen/OpenWeen.UWP#21]
用微博帐号登录出错了！
对第三方应用进行授权时出现错误，请您联系第三方应用的开发者： Weico国际版客户端或者稍后再试。
错误码：21322重定向地址不匹配

**Comment by Tlaster** [comment]
这个项目已经放弃了，后续不会再更新了，微博对第三方的封杀越来越紧
