### ISSUE TITLE
Fix crash ArgumentNull_Generic

### ISSUE THREAD

**Issue by Tlaster** [OpenWeen/OpenWeen.UWP#6]
### Stacktrace (first of multiple)

<pre>System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;;
Microsoft.HockeyApp.Extensibility.Windows.UnhandledExceptionTelemetryModule;CoreApplication_UnhandledErrorDetected;;</pre>

### Reason

ArgumentNull_Generic
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/313809/app_versions/4/crash_reasons/118234927](https://rink.hockeyapp.net/manage/apps/313809/app_versions/4/crash_reasons/118234927)

**Comment by Tlaster** [comment]
很神奇的错误……Native编译之后无法定位准确的调用堆栈，这个错误并不是所有人都会遇到，暂时找不到什么思路

**Comment by huoyaoyuan** [comment]
啊，我的程序也遇到这个神奇的ArgumentNull_Generic，而且在未优化的.Net Native中没有遇到，只有优化之后才会出现。不过Release在VS里直接F5运行还是能看到抛exception的那一行的。
这个问题现在有什么解决方案吗？

**Comment by Tlaster** [comment]
@huoyaoyuan 还没有，目前还没找到在哪抛出的

**Comment by miao17game** [comment]
我也遇到，出现几率非常的低，感觉可能在OnNavigatedTo抛出，但至于，不是很明白。。。。。。

**Comment by huoyaoyuan** [comment]
@miao17game 在某一次SDK更新之后这个问题就消失了。十分怀疑是优化编译器自身的bug。
